import './js/fetchBooks';
// import './js/modal';
// import './js/auth-modal';
// import './js/scroll-up';
// import './js/darkTheme';
import './js/books-by-category';
import './js/allCategories';
import './js/foundations';
import './js/header';
// import './js/auth';
