import './js/fetchBooks';
// import './js/modal';
// import './js/auth-modal';
// import './js/scroll-up';
// import './js/darkTheme';
import './js/category-list';
import './js/allCategories';
import './js/foundations';
// import './js/header';
// import './js/auth';
